apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.rootPassword | b64enc | quote }}