image:
  repository: bank-app/bank-web
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

service:
  port: 8080
  nodePort: 30800

authServer:
  externalUri: "http://localhost:30900"
  internalUri: "http://auth-server:9000"

gateway:
  url: "http://gateway:8090"
