spring:
  application:
    name: auth-server
  config:
    import: "optional:zookeeper:"
  cloud:
    zookeeper:
      connect-string: ${ZK_HOST:localhost:2181}
      config:
        enabled: true

server:
  port: 9000
  servlet:
    session:
      cookie:
        name: AUTHSERVERSESSIONID

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: users

eureka:
  instance:
    prefer-ip-address: true
