apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-web.name" . }}
  labels:
    {{- include "bank-web.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "bank-web.selectorLabels" . | nindent 4 }}