apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-server.name" . }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
data:
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_CLOUD_ZOOKEEPER_ENABLED: "false"
  AUTH_ISSUER_URI: {{ .Values.issuerUri | quote }}
  BANK_WEB_REDIRECT_URI: {{ .Values.redirectUri | quote }}