spring:
  application:
    name: gateway
  config:
    import: "optional:zookeeper:"
  cloud:
    zookeeper:
      connect-string: ${ZK_HOST:localhost:2181}
      config:
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: accounts
              uri: ${ACCOUNTS_URI:lb://accounts}
              predicates:
                - Path=/accounts/**
            - id: cash
              uri: ${CASH_URI:lb://cash}
              predicates:
                - Path=/cash/**
            - id: transfer
              uri: ${TRANSFER_URI:lb://transfer}
              predicates:
                - Path=/transfer/**

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans
