spring:
  application:
    name: accounts
  config:
    import: "optional:zookeeper:"
  cloud:
    zookeeper:
      connect-string: ${ZK_HOST:localhost:2181}
      config:
        enabled: true
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://localhost:3306/accounts}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: false

server:
  port: 8082
  error:
    include-message: always

eureka:
  instance:
    prefer-ip-address: true

kafka:
  topic:
    notifications: notifications
