# MySQL
mysql:
  enabled: true
  rootPassword: secret        # ← меняй здесь; синхронизируй с *.db.password ниже

# Auth Server
auth-server:
  enabled: true
  service:
    nodePort: 30900
  issuerUri: "http://localhost:30900"
  redirectUri: "http://localhost:30800/login/oauth2/code/bank-web"

# Backend сервисы
accounts:
  enabled: true
  db:
    password: secret

cash:
  enabled: true
  db:
    password: secret

transfer:
  enabled: true
  db:
    password: secret

notifications:
  enabled: true

gateway:
  enabled: true

# Frontend
bank-web:
  enabled: true
  service:
    nodePort: 30800
  authServer:
    externalUri: "http://localhost:30900"