global:
  imagePullPolicy: Never
  imageTag: latest

mysql:
  rootPassword: secret

auth-server:
  nodePort: 30900
  issuerUri: "http://localhost:30900"
  redirectUri: "http://localhost:30800/login/oauth2/code/bank-web"

accounts:
  replicaCount: 1

cash:
  replicaCount: 1

transfer:
  replicaCount: 1

notifications:
  replicaCount: 1

gateway:
  replicaCount: 1

bank-web:
  nodePort: 30800
  replicaCount: 1