spring:
  application:
    name: bank-web
  security:
    oauth2:
      client:
        registration:
          bank-web:
            client-id: bank-web-client
            client-secret: bank-web-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          bank-web:
            authorization-uri: ${AUTH_AUTHORIZATION_URI:http://localhost:9000/oauth2/authorize}
            token-uri: ${AUTH_TOKEN_URI:http://localhost:9000/oauth2/token}
            jwk-set-uri: ${AUTH_JWK_SET_URI:http://localhost:9000/oauth2/jwks}
            user-info-uri: ${AUTH_USERINFO_URI:http://localhost:9000/userinfo}
            user-name-attribute: sub

server:
  port: 8080

accounts:
  url: ${ACCOUNTS_URL:http://localhost:8082}

auth:
  url: ${AUTH_URL:http://localhost:9000}
